"""Add helpfull fields to the User and Role tables

Revision ID: 0c3c74b5af9b
Revises: f945ec0ba766
Create Date: 2022-07-06 09:17:34.514359

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0c3c74b5af9b"
down_revision = "f945ec0ba766"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("role", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, "role", ["title"])
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "created_at")
    op.drop_constraint(None, "role", type_="unique")
    op.drop_column("role", "created_at")
    # ### end Alembic commands ###
