blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/srubtsov/Open-CRM/discussions
    about: If you have a support question or need help getting Open-CRM to work, please use GitHub Discussions.